create table REGIONS
(
	REGION_ID INT IDENTITY PRIMARY KEY,
	REGION_NAME char(25) 
);

create table COUNTRIES
(
	COUNTRY_ID char(2) PRIMARY KEY,
	COUNTRY_NAME char(25) , 
	REGION_ID INT  
);

create table LOCATIONS
(
	LOCATION_ID INT PRIMARY KEY,
	STREET_ADDRESS char(40) , 
	POSTAL_CODE char(20), 
	CITY char(25), 
	STATE_PROVINCE char(25), 
	COUNTRY_ID char(2)  
);

create table DEPARTMENTS
(
	DEPARTMENT_ID INT PRIMARY KEY,
	DEPARTMENT_NAME char(40), 
	MANAGER_ID INT, 
	LOCATION_ID INT, 
);

create table JOBS
(
	JOB_ID char(25) PRIMARY KEY,
	JOB_TITLE char(40), 
	MIN_SALARY INT, 
	MAX_SALARY INT, 
);


create table EMPLOYEES
(
	EMPLOYEE_ID INT PRIMARY KEY,
	FIRST_NAME char(25) , 
	LAST_NAME char(25) ,
	EMAIL char(25) ,
	PHONE_NUMBER char(25) ,
	HIRE_DATE date ,
	JOB_ID char(25) ,
	SALARY INT ,
	COMMISSION_PCT FLOAT,
	MANAGER_ID INT, 
	DEPARTMENT_ID INT
);

create table JOB_HISTORY
(
	EMPLOYEE_ID INT ,
	START_DATE date , 
	END_DATE date , 
	JOB_ID char(25) , 
	DEPARTMENT_ID INT ,
	CONSTRAINT HISTORY PRIMARY KEY (EMPLOYEE_ID, START_DATE)
);

ALTER TABLE COUNTRIES ADD CONSTRAINT FK_coun_reg FOREIGN KEY (REGION_ID)  REFERENCES REGIONS (REGION_ID);
ALTER TABLE LOCATIONS ADD CONSTRAINT FK_loc_coun FOREIGN KEY (COUNTRY_ID)  REFERENCES COUNTRIES (COUNTRY_ID);
ALTER TABLE DEPARTMENTS ADD CONSTRAINT FK_dep_loc FOREIGN KEY (LOCATION_ID)  REFERENCES LOCATIONS (LOCATION_ID);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT FK_dep_man FOREIGN KEY (MANAGER_ID)  REFERENCES EMPLOYEES (EMPLOYEE_ID);
ALTER TABLE JOB_HISTORY ADD CONSTRAINT FK_jobh_emp FOREIGN KEY (EMPLOYEE_ID)  REFERENCES EMPLOYEES (EMPLOYEE_ID);
ALTER TABLE JOB_HISTORY ADD CONSTRAINT FK_jobh_job FOREIGN KEY (JOB_ID)  REFERENCES JOBS (JOB_ID);
ALTER TABLE JOB_HISTORY ADD CONSTRAINT FK_jobh_dep FOREIGN KEY (DEPARTMENT_ID)  REFERENCES DEPARTMENTS  (DEPARTMENT_ID);
ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_emp_dep FOREIGN KEY (DEPARTMENT_ID)  REFERENCES DEPARTMENTS  (DEPARTMENT_ID);
ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_emp_man FOREIGN KEY (MANAGER_ID)  REFERENCES EMPLOYEES (EMPLOYEE_ID);

DROP TABLE REGIONS;
DROP TABLE COUNTRIES;
DROP TABLE LOCATIONS;
DROP TABLE DEPARTMENTS;
DROP TABLE JOBS;
DROP TABLE EMPLOYEES;
DROP TABLE JOB_HISTORY;

ALTER TABLE COUNTRIES DROP CONSTRAINT FK_coun_reg;
ALTER TABLE LOCATIONS DROP CONSTRAINT FK_loc_coun;
ALTER TABLE DEPARTMENTS DROP CONSTRAINT FK_dep_loc;
ALTER TABLE DEPARTMENTS DROP CONSTRAINT FK_dep_man;
ALTER TABLE JOB_HISTORY DROP CONSTRAINT FK_jobh_emp;
ALTER TABLE JOB_HISTORY DROP CONSTRAINT FK_jobh_job;
ALTER TABLE JOB_HISTORY DROP CONSTRAINT FK_jobh_dep;
ALTER TABLE EMPLOYEES DROP CONSTRAINT FK_emp_dep;
ALTER TABLE EMPLOYEES DROP CONSTRAINT FK_emp_man;

select * from EMPLOYEES  inner join EMPLOYEES EMP2 on EMPLOYEES.MANAGER_ID = EMP2.EMPLOYEE_ID;

select * from EMPLOYEES inner join DEPARTMENTS on EMPLOYEES.EMPLOYEE_ID = DEPARTMENTS.DEPARTMENT_ID;
select * from LOCATIONS;
select * from EMPLOYEES;